heroku: snowpack build instead of dev server (error)
Error: ENOSPC: System limit for number of file watchers reached, watch '/app/node_modules/date-fns/esm/locale/af/package.json'